from __future__ import annotations

import math
import re
from typing import Any, Dict, Iterable, List, Optional

_EMBED_SECONDS_RE = re.compile(r"EMBED DEBUG > .* seconds=(?P<seconds>\d+(?:\.\d+)?)")


def percentile(values: Iterable[float], p: float) -> float:
    ordered = sorted(float(v) for v in values if v is not None)
    if not ordered:
        return 0.0
    if len(ordered) == 1:
        return ordered[0]
    p = max(0.0, min(100.0, float(p)))
    rank = (len(ordered) - 1) * (p / 100.0)
    lower = math.floor(rank)
    upper = math.ceil(rank)
    if lower == upper:
        return ordered[lower]
    weight = rank - lower
    return ordered[lower] * (1.0 - weight) + ordered[upper] * weight


def recommend_timeout(
    observed_seconds: Iterable[float],
    minimum: int,
    p95_multiplier: float = 1.5,
    max_multiplier: float = 1.25,
    pad_seconds: int = 0,
) -> int:
    observed = [float(v) for v in observed_seconds if float(v) > 0]
    if not observed:
        return int(minimum)
    p95 = percentile(observed, 95)
    peak = max(observed)
    recommended = max(minimum, math.ceil(p95 * p95_multiplier), math.ceil(peak * max_multiplier))
    return int(recommended + max(0, int(pad_seconds)))


def parse_embed_debug_seconds(log_text: str) -> List[float]:
    values: List[float] = []
    for match in _EMBED_SECONDS_RE.finditer(log_text or ""):
        values.append(float(match.group("seconds")))
    return values


def calibrate_timeout_recommendations(
    runs: List[Dict[str, Any]],
    embed_seconds: Optional[List[float]] = None,
) -> Dict[str, Any]:
    embed_seconds = embed_seconds or []
    llm_durations = [
        float((run.get("diagnostics") or {}).get("llm_duration_seconds") or 0.0)
        for run in runs
        if isinstance(run, dict)
    ]
    wall_durations = [float(run.get("wall_seconds") or 0.0) for run in runs if isinstance(run, dict)]
    non_llm_durations = []
    for run in runs:
        if not isinstance(run, dict):
            continue
        diagnostics = run.get("diagnostics") or {}
        wall = float(run.get("wall_seconds") or 0.0)
        llm = float(diagnostics.get("llm_duration_seconds") or 0.0)
        non_llm_durations.append(max(0.0, wall - llm))
    mcp_observed = sorted([v for v in non_llm_durations + embed_seconds if v > 0])

    embed_timeout = max(
        60,
        recommend_timeout(embed_seconds, minimum=120, p95_multiplier=1.5, max_multiplier=1.25, pad_seconds=5),
    )
    llm_timeout = recommend_timeout(llm_durations, minimum=120, p95_multiplier=1.5, max_multiplier=1.25, pad_seconds=10)
    mcp_timeout = max(
        embed_timeout,
        recommend_timeout(mcp_observed, minimum=60, p95_multiplier=1.5, max_multiplier=1.25, pad_seconds=10),
    )
    acp_floor = llm_timeout + max(30, math.ceil(mcp_timeout * 0.25))
    acp_timeout = max(
        acp_floor,
        recommend_timeout(wall_durations, minimum=180, p95_multiplier=1.35, max_multiplier=1.2, pad_seconds=15),
    )
    if acp_timeout <= llm_timeout:
        acp_timeout = llm_timeout + 30

    llm_failures = []
    for run in runs:
        diagnostics = (run or {}).get("diagnostics") or {}
        status = diagnostics.get("llm_status")
        if status and status != "ok":
            llm_failures.append(
                {
                    "flow": run.get("flow"),
                    "llm_status": status,
                    "fallback_reason": run.get("fallback_reason"),
                }
            )

    return {
        "observed": {
            "runs": len(runs),
            "wall_seconds_p95": round(percentile(wall_durations, 95), 3),
            "llm_seconds_p95": round(percentile(llm_durations, 95), 3),
            "mcp_proxy_seconds_p95": round(percentile(mcp_observed, 95), 3),
            "embed_seconds_p95": round(percentile(embed_seconds, 95), 3),
        },
        "recommended_env": {
            "EMBED_TIMEOUT": embed_timeout,
            "STUDY_AGENT_MCP_TIMEOUT": mcp_timeout,
            "LLM_TIMEOUT": llm_timeout,
            "ACP_TIMEOUT": acp_timeout,
        },
        "llm_failures": llm_failures,
    }


def render_env_fragment(calibration: Dict[str, Any]) -> str:
    env = calibration.get("recommended_env") or {}
    lines = ["# Generated by scripts/calibrate_timeouts.py"]
    for key in ("EMBED_TIMEOUT", "STUDY_AGENT_MCP_TIMEOUT", "LLM_TIMEOUT", "ACP_TIMEOUT"):
        if key in env:
            lines.append(f"{key}={env[key]}")
    return "\n".join(lines) + "\n"
